[ADD] 호스팅 상품 등록, 리스트 조회, 삭제 기능 추가
wecode-bootcamp-korea/38-2nd-WeFrip-backend pull request #18
Opened 2022-11-10 10:16 UTC by Eunsong-Park

- 호스팅 상품 등록 기능 추가
- 내가 만든 호스팅 상품 리스트 조회 추가
- 호스팅 상품 삭제 기능 추가

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 호스팅 상품 등록, 리스트 조회, 삭제 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 호스팅 상품 등록
- 유저가 호스팅하고자 하는 상품을 등록할 수 있습니다.
- 상품 사진을 최대 5장 등록할 수 있습니다. 그 중 첫 번째 사진은 썸네일 이미지로 따로 등록됩니다.

2. 해당 유저가 만든 호스팅 상품 리스트 조회

3. 호스팅 상품 삭제

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항
- postman을 이용한 백엔드 테스트는 마치고 프론트엔드와 통신하는 과정 중에 있습니다.
일단 PR부터 올리고 미비한 부분을 금일까지 수정하도록 하겠습니다!

2022-11-10 14:50 UTC, sangwoong03 requested changes

2022-11-10 14:50 UTC, sangwoong03 commented on models/productDao.js
> +    WHERE s. product_id = ?;`,
공백 삭제해주세요!
```suggestion
    WHERE s.product_id = ?;`,
```

2022-11-10 14:50 UTC, sangwoong03 commented on models/productDao.js
> +    FROM product_images AS p
Alias (별칭)은 줄이는 본 테이블 명의 의미를 충분히 담고 있어야 한다고 생각합니다.

`pi`정도로 줄여주면 좋을 것 같습니다.
```suggestion
    FROM product_images AS pi
```

2022-11-10 14:50 UTC, sangwoong03 commented on controllers/productController.js
> +  }
productImagesUrl이라는 변수에 files 배열에 해당하는 값들을 얕은 복사를 다음과 같이 작성할 수 있을 것 같습니다~!
```suggestion
  const productImagesUrl = [...files]; 
```

2022-11-10 15:39 UTC, Eunsong-Park commented on models/productDao.js
> +    WHERE s. product_id = ?;`,
공백 삭제하겠습니다!

2022-11-10 15:40 UTC, Eunsong-Park commented on models/productDao.js
> +    FROM product_images AS p
p -> pi 로 alias 수정하겠습니다!

2022-11-11 01:26 UTC, sangwoong03 approved these changes
고생하셨습니다! 👍

2022-11-11 01:27 UTC, merged