[ADD] DB migrations 파일 추가
wecode-bootcamp-korea/38-2nd-WeFrip-backend pull request #2
Opened 2022-11-01 09:32 UTC by Eunsong-Park

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- DB 생성을 위해 migration 파일을 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 백엔드 작업 전 공통 데이터베이스 테이블을 생성하기 위해 migration 파일을 추가했습니다.
- 총 18개의 migration 파일

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 테이블 생성을 위해 migration 파일을 만드는 작업에 익숙해졌습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-11-01 10:10 UTC, sangwoong03 requested changes
고생하셨습니다!

제가 놓치는 부분도 있을 것이라 생각되어 수정 이후에도 다시 한 번 꼼꼼히 확인할게요~!

2022-11-01 10:10 UTC, sangwoong03 commented on db/migrations/20221101083518_create_payment_status_table.sql
> +DROP TABLE payment_status;
payments를 실제 팀 기획에서 구현하지 않는 것으로 인지하고 있습니다.

해당 내용은 서비스 기획을 하는 입장에서 고려해볼만 사항으로 인사이트를 드리고자 전달했던 내용입니다!

필요한 테이블이 아니라고 판단되는데 weFrip 팀원분들은 어떻게 생각하시나요???

2022-11-01 10:10 UTC, sangwoong03 commented on db/migrations/20221101083712_create_payments_table.sql
> +DROP TABLE payments;
해당 부분도 동일한 사항입니다!

2022-11-01 10:10 UTC, sangwoong03 commented on db/migrations/20221101084237_create_products_table.sql
> +  participants INT DEFAULT 1,
아마 host가 생성할 때 반드시 필요한 내용이라고 생각이 됩니다!

참여자 수 설정을 안했을 때 1명만 참석하게 되는 경우,, 서비스를 운영할 필요가 있을까 고민해볼만 내용인 것 같네요!

2022-11-01 10:10 UTC, sangwoong03 commented on db/migrations/20221101084237_create_products_table.sql
> +  last_date DATE NULL,
시작 종료 날짜 이외에 시간은 중요하지 않은 데이터인가요??

2022-11-01 10:10 UTC, sangwoong03 commented on db/migrations/20221101085841_create_orders_table.sql
> +  payment_id INT DEFAULT 1,
해당 부분도 payments와 관련되었기 때문에 다시 고민해보시면 좋을 것 같습니다.

2022-11-01 11:58 UTC, Eunsong-Park commented on db/migrations/20221101083518_create_payment_status_table.sql
> +DROP TABLE payment_status;
팀원들과 협의하여 payments 부분은 삭제하기로 결정했습니다!

2022-11-01 12:02 UTC, Eunsong-Park commented on db/migrations/20221101084237_create_products_table.sql
> +  participants INT DEFAULT 1,
products 테이블 내 price, description, thumbnail_image_url, participants 는 모두 NOT NULL 로 설정하겠습니다.

participants 는 서비스 단에서 5명 이상만 데이터가 들어가도록 로직을 짜보겠습니다!

2022-11-01 12:17 UTC, Eunsong-Park commented on db/migrations/20221101084237_create_products_table.sql
> +  last_date DATE NULL,
해당 데이터는 시작/종료 일자만 들어가는 것으로 하고,
스케줄 테이블을 따로 만들어서 해당 날짜의 스케줄 데이터를 작성할 수 있도록 하겠습니다.

2022-11-02 03:04 UTC, sangwoong03 approved these changes
LGTM 👍

2022-11-02 03:04 UTC, merged