[ADD] 카카오 로그인 구현 및 기타 수정사항 반영
wecode-bootcamp-korea/38-2nd-WeFrip-backend pull request #6
Opened 2022-11-04 13:14 UTC by Eunsong-Park

- 카카오 소셜 로그인 기능 추가
- auth, error 유틸 기능 추가
- 카카오 서버 통신을 위한 axios 모듈 추가

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- users 관련 CRU 기능 구현 (D 제외)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카카오 소셜 로그인 기능 (POST users/signin)
- 카카오 토큰을 이용해서 유저 정보를 받아옵니다.
- 받은 유저정보가 기존 db에 존재한다면 저장하지 않습니다.
- 받은 유저정보가 기존 db에 존재하지 않는다면 신규 회원으로 간주하고 db에 저장합니다.
- 카카오 서버에서 받아온 유저정보 중 카카오 아이디를 매칭시켜 우리 db의 유저 아이디를 조회합니다.
- 해당 유저 아이디를 사용하여 jwt를 생성하고 반환합니다.

2. auth, error 유틸 기능 추가
- 로그인 및 토큰검증 미들웨어를 위해 auth 파일을 추가했습니다.
- 글로벌 에러핸들링을 위해 error 파일을 추가했습니다.

3. axios 모듈 추가
- 카카오 서버와 통신을 위해 axios 모듈을 추가했습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 백엔드에서 다른 서버로 요청을 보내고 응답을 받는 방법에 대해서 알게 되었습니다. (axios)
- 새로운 기능을 구현하기 위해 공식문서를 어떻게 읽는지 알게 되었습니다.
- postman을 이용하여 oauth를 포함한 테스트를 어떻게 수행하는지 학습하였습니다.
- 로그인이라는 한 가지 기능을 구현하기 위해 프론트엔드 / 카카오 서버와 통신을 여러 번 거쳐야 한다는 점을 새롭게 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-11-07 02:29 UTC, Eunsong-Park commented
처음 카카오 소셜 로그인 시, 유저의 프로필 이미지는 카카오 프로필 이미지를 사용합니다.
로그인 된 상태에서 유저가 프로필 이미지를 변경 시, 해당 이미지는 aws s3에 저장 후 변경됩니다.

2022-11-07 07:02 UTC, sangwoong03 requested changes

2022-11-07 07:02 UTC, sangwoong03 commented on utils/auth.js
> +  // 1) Getting token and check if it is there
주석을 통해 코드를 설명하고 구분하는 것은 좋아보입니다!

다만 코드의 길이가 길지 않고, 코드를 수정했을 때 주석까지 수정을 해야하는 필요성이 생기게 됩니다.

만약 코드를 수정하였는데 주석을 수정하지 않은 경우, 다른 개발자들과 협업을 할 때 혼동이 생길 수 있습니다.

코드 자체로 설명하기가 어렵지 않다면 주석은 삭제해주는 것이 좋아보이네요!

2022-11-07 07:02 UTC, sangwoong03 commented on services/userService.js
> +};
async await 키워드를 사용했기 떄문에 `.then`을 사용하여 비동기처리를 하지 않아도 될 것 같습니다.

```suggestion
const getKakaoUserInfo = async (kakaoAccessToken) => {
  const options = {
    method: 'POST',
    url: 'https://kapi.kakao.com/v2/user/me',
    headers: {
      'Content-type': 'application/x-www-form-urlencoded;charset=utf-8',
      'Authorization': `Bearer ${kakaoAccessToken}`
    }}
  const kakaoUserInfo = await axios.request(options)
  
  return kakaoUserInfo
};
```

2022-11-07 07:02 UTC, sangwoong03 commented on services/userService.js
> +  const [ userId ] = await userDao.getUserIdByKakaoId(kakaoId);
DAO에서 `{userId: number}` 정보만 보낼 수 있도록 수정해주세요~!

2022-11-07 07:02 UTC, sangwoong03 commented on services/userService.js
> +  return jwt.sign({ userId: userId.userId }, process.env.JWT_SECRET, { expiresIn: process.env.JWT_EXPIRES_IN });
jwt 해싱을 위한 알고리즘 값 설정을 해주세요!
```suggestion
  return jwt.sign({ userId: userId.userId }, process.env.JWT_SECRET,
    {
      algorithm: process.env.ALGORITHM,
      expiresIn: process.env.JWT_EXPIRES_IN
    });
```

2022-11-07 07:02 UTC, sangwoong03 commented on services/userService.js
> +  const [ userId ] = await userDao.getUserIdByKakaoId(kakaoUserInfo.id);
해당 부분도 마찬가지 입니다~!

2022-11-07 07:02 UTC, sangwoong03 commented on services/userService.js
> +  const [ userInfo ] = await userDao.getUserById(userId);
해당 부분도 수정해주세요~!

2022-11-07 07:02 UTC, sangwoong03 commented on services/userService.js
> +  )
userId가 원래 생성되어 있는 로직이 맞는 것인가요?!

2022-11-07 07:02 UTC, sangwoong03 commented on models/userDao.js
> +  let gender = kakaoUserInfo['kakao_account'].gender;
해당 부분은 service에서 비구조화 할당을 통해 각 데이터를 받아오는 것으로 수정해주세요!

2022-11-07 07:02 UTC, sangwoong03 commented on app.js
> +console.log('Region: ', AWS.config.region);
해당 코드를 통해 구현할 수 있는 기능이 있을까요??

2022-11-07 07:02 UTC, sangwoong03 commented on controllers/userController.js
> +        message: 'Invalid file path'
반환하는 에러 메시지 대문자로 통일해주셨는데 이 부분도 대문자로 통일해주면 좋을 것 같습니다!

```suggestion
        message: 'INVALID_FILE_PATH'
```

2022-11-07 07:02 UTC, sangwoong03 commented on models/userDao.js
> +    ) VALUES (?, ?, ?, ?, ?, ?);`, [ kakaoId, nickname, profileImageUrl, email, birthday, genderId ]
마이너하지만 배열로 매핑하는 부분 한칸 띄워서 작성해주시죠!

```suggestion
    ) VALUES (?, ?, ?, ?, ?, ?);`,
    [ kakaoId, nickname, profileImageUrl, email, birthday, genderId ]
```

2022-11-07 08:33 UTC, Eunsong-Park commented on utils/auth.js
> +  // 1) Getting token and check if it is there
네 말씀하신대로 코드에 주석까지 관리하려면 불필요한 공수가 들어가겠군요. 삭제하도록 하겠습니다!

2022-11-07 08:45 UTC, Eunsong-Park commented on services/userService.js
> +};
```suggestion
const getKakaoUserInfo = async (kakaoAccessToken) => {
  let kakaoUserInfo;

  await axios({
    method: 'POST',
    url: 'https://kapi.kakao.com/v2/user/me',
    headers: {
      'Content-type': 'application/x-www-form-urlencoded;charset=utf-8',
      'Authorization': `Bearer ${kakaoAccessToken}`
    }
    }).then((result) => {
      kakaoUserInfo = result.data;
    })
  
  return kakaoUserInfo
};
```


const getKakaoUserInfo = async (kakaoAccessToken) => {

  const result = await axios({
    method: 'POST',
    url: 'https://kapi.kakao.com/v2/user/me',
    headers: {
      'Content-type': 'application/x-www-form-urlencoded;charset=utf-8',
      'Authorization': `Bearer ${kakaoAccessToken}`
    }
  })

  const kakaoUserInfo = result.data;
  
  return kakaoUserInfo
};

2022-11-07 09:28 UTC, Eunsong-Park commented on services/userService.js
> +  const [ userId ] = await userDao.getUserIdByKakaoId(kakaoId);
리뷰 내용을 이해하지 못했습니다. 죄송하지만 다시 설명해주실 수 있으신가요?

간략히 해당 내용을 부가 설명을 드리자면,
Service 단의 해당 함수 storeKakaoUserInfo는 
카카오 아이디를 뽑아서 DAO의 getUserIdByKakaoId 함수를 이용하여 
users 테이블 내용 중 { userId : number }  데이터만 가져와서
해당 데이터가 있으면 (우리 db에 id가 조회되면) 카카오에서 가져온 유저 정보를 저장하는 것을 건너뛰고
해당 데이터가 없으면 (우리 db에 id가 조회되지 않으면) 카카오에서 가져온 유저 정보를 저장하는 로직입니다!

2022-11-07 09:35 UTC, Eunsong-Park commented on services/userService.js
> +  return jwt.sign({ userId: userId.userId }, process.env.JWT_SECRET, { expiresIn: process.env.JWT_EXPIRES_IN });
알고리즘 값 설정을 위해 코드를 추가하겠습니다.
.env.sample 파일에도 알고리즘 값을 기재하여 push 하겠습니다!

2022-11-07 09:40 UTC, Eunsong-Park commented on services/userService.js
> +  )
해당 내용은 기 생성된 유저 정보를 업데이트 (PATCH)하는 로직으로
loginRequired 미들웨어를 거쳐 userId를 가져올 수 있을 것으로 보입니다.

혹시 제가 잘못 알고 있는 부분이 있다면 다시 알려주실 수 있으신가요?

2022-11-07 11:42 UTC, Eunsong-Park commented on models/userDao.js
> +  let gender = kakaoUserInfo['kakao_account'].gender;
`const storeKakaoUserInfo = async(kakaoUserInfo) => {
  
  let { kakaoId, nickname, profileImageUrl, email, birthday, gender, genderId } = {
    kakaoId : kakaoUserInfo.id,
    nickname : kakaoUserInfo['kakao_account'].profile.nickname,
    profileImageUrl : kakaoUserInfo['kakao_account'].profile['profile_image_url'],
    email : kakaoUserInfo['kakao_account'].email,
    birthday : kakaoUserInfo['kakao_account'].birthday,
    gender : kakaoUserInfo['kakao_account'].gender,
    genderId : 0
  }

  if (gender === 'male') {
    genderId = 1;
  } else if (gender === 'female') {
    genderId = 2;
  } else {
    genderId = 3;
  }
  
  const [ userId ] = await userDao.getUserIdByKakaoId(kakaoId);

  if (!userId) {
    await userDao.storeKakaoUserInfo(kakaoId, nickname, profileImageUrl, email, birthday, genderId)
  }
};`

비구조화 할당은 어떻게 적용해야 할지 잘 모르겠습니다...
service 내에서 이런 식으로 수정하면 될까요?

2022-11-07 11:47 UTC, Eunsong-Park commented on app.js
> +console.log('Region: ', AWS.config.region);
app.js를 실행하면 aws credential이 잘 적용되었는지 확인한 후 access key 와 region을 콘솔에서 확인할 수 있으면 좋을 것 같아서 넣어뒀습니다.
없는 것이 더 나을까요?

2022-11-07 11:48 UTC, Eunsong-Park commented on controllers/userController.js
> +        message: 'Invalid file path'
네 에러메세지는 대문자로 통일하겠습니다!

2022-11-07 11:50 UTC, Eunsong-Park commented on models/userDao.js
> +    ) VALUES (?, ?, ?, ?, ?, ?);`, [ kakaoId, nickname, profileImageUrl, email, birthday, genderId ]
넵 해당하는 부분은 모두 개행하고 작성하도록 하곘습니다!

2022-11-07 12:06 UTC, Eunsong-Park commented on services/userService.js
> +};
테스트 결과, 문제가 없어 위 코드대로 수정하도록 하겠습니다!

2022-11-07 15:11 UTC, sangwoong03 commented on models/userDao.js
> +  let gender = kakaoUserInfo['kakao_account'].gender;
은송님! 지금 `kakaoUserInfo`객체에 담기는 `kakao_account`역시 객체로 보여지는데 이 부분도 비구조화 할당을 통해 하위 데이터를 불러올 수 있을 것 같아요!

```suggestion
  const kakaoId = kakaoUserInfo.id 
  const { email, birthday, gender } = kakaoUserInfo.kakao_account;
  const { nickname, profileImageUrl } = kakaoUserInfo.kakao_account.profile;
```

2022-11-07 15:12 UTC, sangwoong03 commented on app.js
> +console.log('Region: ', AWS.config.region);
해당 목적이라면 디버깅을 할 때 굉장히 유용할 것 같습니다!

다만, 현재 AWS의 accessKeyId와 region을 환경변수로 관리하고 있기 때문에 해당 코드를 배포 단계에서 올릴 필요는 없어보이네요~!

2022-11-07 15:24 UTC, sangwoong03 requested changes
리뷰에 댓글 달아주는 것 자체로도 좋은 커뮤니케이션을 보여주는 것이라고 생각이 드네요!!

리뷰를 꼼꼼하게 읽었다는 의미로도 해석되니 너무 감사합니다~!

리베이스 진행해주시고 추가 리뷰 반영해주세요 👍

2022-11-07 15:24 UTC, sangwoong03 commented on models/userDao.js
> +  }
만약 객체 (enum)를 통해 매핑을 하게 된다면 다음과 같이 사용할 수 있을 것 같습니다.

```suggestion
  let genderId = 0;
  const GENDER = Object.freeze({
    male : 1,
    female: 2,
    other: 3
  })
  genderId = GENDER[gender]
```

2022-11-08 04:38 UTC, Eunsong-Park commented on models/userDao.js
> +  let gender = kakaoUserInfo['kakao_account'].gender;
오 이런 식으로 작성하면 훨씬 깔끔해지는군요! 감사합니다.
그렇게 수정하도록 하겠습니다!

2022-11-08 04:41 UTC, Eunsong-Park commented on app.js
> +console.log('Region: ', AWS.config.region);
말씀대로 배포단계에서는 불필요한 코드인 것으로 보이네요! 
삭제하도록 하겠습니다!

2022-11-08 04:57 UTC, Eunsong-Park commented on models/userDao.js
> +  }
자료를 봐도 이해가 잘 안갔는데 이렇게 사용할 수 있겠네요! 적용해서 수정하겠습니다. 감사합니다~

2022-11-08 08:08 UTC, sangwoong03 approved these changes
gender 데이터 변경 관련 부분 나중에 따로 분리하거나, model/dao에서 관리할 수 있도록 리팩토링만 하면 좋을 것 같습니다~! 

LGTM 👍

2022-11-08 08:08 UTC, merged