listpage  기능 구현
wecode-bootcamp-korea/38-2nd-WeFrip-backend pull request #7
Opened 2022-11-06 05:58 UTC by csongin

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- main category, sub category 조회 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리스트 페이지 조회 기능 구현
- main category name, sub category name을 받아 전체 products를 조회합니다.
- 각각의 가격 오름차순, 내림차순으로 정렬하여 조회합니다.
- 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 이번에도 역시 query 문을 많이 사용하였습니다.
- json_object로 묶인 값들을 필터링으로 정렬하는 것에 실패하였습니다.

<br />

## :: 기타 질문 및 특이 사항
- json_object에 묶여있는 값들에 ORDER BY 적용이 안되는데, 다른 정렬할 수 있는 방법이 있을까요?

2022-11-07 08:29 UTC, sangwoong03 requested changes

2022-11-07 08:29 UTC, sangwoong03 commented on models/productDao.js
> +  const filtering = appDataSource.query(`
await 키워드를 통해 비동기 처리를 해주세요~!
```suggestion
  const filtering = await appDataSource.query(`
```

2022-11-07 08:29 UTC, sangwoong03 commented on services/productService.js
> +}
삼항연산자 사용하는 방법도 있으니 참고해주세요!
```suggestion
    return sort
    ? await productDao.mainCategoryFiltering(mainCategoryName, sort);
    : await productDao.getProductMainCategories(mainCategoryName);
 
```

2022-11-07 08:29 UTC, sangwoong03 commented on models/productDao.js
> +  const filtering = appDataSource.query(`
이 부분도 비동기 함수 처리를 위해 await 키워드를 넣어주세요!
```suggestion
  const filtering = await appDataSource.query(`
```

2022-11-07 08:46 UTC, csongin commented on services/productService.js
> +}
넵!! 날짜 필터링 기능도 구현해서 if문 사용하였습니다.

2022-11-08 08:10 UTC, sangwoong03 requested changes
송인님 협업하는 코드의 통일성을 위해 DAO에서 데이터 사용 부분을 수정해주세요!

현재 `${ data }`를 통해 직접 값을 대입하고 있는 부분을 배열을 활용한 parameter mapping 방식으로 수정해주세요!

2022-11-08 14:59 UTC, sangwoong03 approved these changes
고생하셨습니다!! 👍

2022-11-08 14:59 UTC, merged