[ADD] 상세페이지 구현
wecode-bootcamp-korea/38-2nd-WeFrip-backend pull request #8
Opened 2022-11-07 04:10 UTC by ShinInHuck

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상세페이지 구현 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상세페이지 구현(백엔드)
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- query문으로 jsonarrayagg, json_objcet etc 학습하게 되었습니다. 

<br />

## :: 기타 질문 및 특이 사항

2022-11-07 07:10 UTC, sangwoong03 requested changes

2022-11-07 07:10 UTC, sangwoong03 commented on routes/detailProductRouter.js
> +module.exports = router;
product와 관련된 라우팅 코드는 `productRouter.js` 와 같은 하나의 파일에서 엔드포인트 라우팅을 관리해주시면 됩니다!

2022-11-07 07:10 UTC, sangwoong03 commented on routes/index.js
> +router.use('/products', detailProductRouter);
`productRouter.js` 파일에서 관리할 경우 다음과 같이 수정할 수 있을 것 같습니다~!
```suggestion
const detailProductRouter = require('./detailProductRouter');

router.use('/products', productRouter);
```

2022-11-07 07:10 UTC, sangwoong03 commented on services/detailProductService.js
> +}
해당 부분 indentation(들여쓰기 간격) 수정해주세요!

2022-11-07 07:10 UTC, sangwoong03 commented on models/detailProductDao.js
> +}
쿼리문 포매팅 수정해주세요~!

```suggestion
  const detailProduct = await appDataSource.query(`
    SELECT DISTINCT
      p.name, 
      p.price,
      p.discount_rate AS discountRate, 
      p.thumbnail_image_url AS thumbnailImageUrl,
      p.description,
      l.name,
      l.latitude,
      l.longitude,
      (
        SELECT 
          JSON_ARRAYAGG(pi.image_url)
        FROM product_images AS pi
        JOIN products AS p ON pi.product_id = p.id
        WHERE p.id = ${productId}
       ) AS productImages,              
      JSON_ARRAYAGG(
        JSON_OBJECT(
        'content', s.content,
        'startTime', s.start_time,
        'finishTime', s.finish_time)) AS schedules
    FROM products AS p
    JOIN schedules AS s ON s.product_id = p.id
    JOIN location AS l ON p.location_id = l.id
    WHERE p.id = ${productId}`)
    
    return detailProduct;
} 
```

2022-11-07 11:53 UTC, sangwoong03 requested changes
인혁님 고생하셨습니다!
package-lock.json 파일 수정이 있어보이는데, 혹시 개발하시면서 다른 모듈을 설치하거나 삭제했던 이력이 있었나요?

main 브랜치에 병합되면 차후 개발에 영향을 미칠 수 있을 것 같은데 확인 부탁드립니다!

2022-11-08 07:00 UTC, ShinInHuck commented
멘토님 확인해봤는데 이상없습니다. 감사합니다:)

2022-11-08 08:11 UTC, sangwoong03 requested changes
package-lock.json 캐시가 제대로 삭제되지 않은 것 같습니다~!

conflct 해결 보다는 캐시를 삭제하여 push된 파일 이력을 삭제하는 것이 용이할 것으로 판단되니 한번 더 수정해주세요!

2022-11-08 15:00 UTC, sangwoong03 requested changes
rebase 및 conflict 해결해주세요!!

2022-11-09 07:44 UTC, sangwoong03 approved these changes
고생하셨습니다!! 🙌

2022-11-09 07:44 UTC, merged